#!/bin/sh

NO_GPS=0
NO_TEMP=0
NO_IAQ=0
NO_UV=0

while test $# -gt 0 ; do
  if test "$1" = "--no-gps"; then NO_GPS=1; shift; continue; fi
  if test "$1" = "--no-temp"; then NO_TEMP=1; shift; continue; fi
  if test "$1" = "--no-iaq"; then NO_IAQ=1; shift; continue; fi
  if test "$1" = "--no-uv"; then NO_UV=1; shift; continue; fi
done

resp=$(curl --silent -H 'Content-Type: application/json' http://127.0.0.1:3232)
if [ -n "$resp" ]
then
  temp=0
  if [ -n $(echo $resp | jq -r '.temp // empty') ]
  then
    temp=$(echo $resp | jq '.temp' | xargs printf '%.*f\n' 1 $a)
  fi

  humy=0
  if [ -n $(echo $resp | jq -r '.humy // empty') ]
  then
    humy=$(echo $resp | jq '.humy' | xargs printf '%.*f\n' 1 $a)
  fi

  pres=0
  if [ -n $(echo $resp | jq -r '.pres // empty') ]
  then
    pres=$(echo $resp | jq '.pres' | xargs printf '%.*f\n' 1 $a)
  fi

  iaq=0
  if [ -n $(echo $resp | jq -r '.iaq // empty') ]
  then
    iaq=$(echo $resp | jq '.iaq' | xargs printf '%.*f\n' 1 $a)
  fi

  gasp=0
  if [ -n $(echo $resp | jq -r '.gasp // empty') ]
  then
    gasp=$(echo $resp | jq '.gasp' | xargs printf '%.*f\n' 1 $a)
  fi

  ulvi=0
  if [ -n $(echo $resp | jq -r '.ulvi // empty') ]
  then
    ulvi=$(echo $resp | jq '.ulvi' | xargs printf '%.*f\n' 1 $a)
  fi

  visb=0
  if [ -n $(echo $resp | jq -r '.visb // empty') ]
  then
    visb=$(echo $resp | jq '.visb' | xargs printf '%.*f\n' 1 $a)
  fi

  latt=0
  if [ -n $(echo $resp | jq -r '.latt // empty') ]
  then
    latt=$(echo $resp | jq '.latt' | xargs -I {} echo "{}*10^-7" | eva | xargs printf '%.*f\n' 8 $a)
  fi

  long=0
  if [ -n $(echo $resp | jq -r '.long // empty') ]
  then
    long=$(echo $resp | jq '.long' | xargs -I {} echo "{}*10^-7" | eva | xargs printf '%.*f\n' 8 $a)
  fi

  altt=0
  if [ -n $(echo $resp | jq -r '.altt // empty') ]
  then
    altt=$(echo $resp | jq '.altt' | xargs -I {} echo "{}/1000" | bc )
  fi

  echo -n "{\"text\": \""
  if [ $NO_GPS = 0 ]
  then
    echo -n " ${altt}m [<span color='#aaaaaa'>${latt} ${long}</span>]"
  fi
  if [ $NO_TEMP = 0 ]
  then
    if [ $NO_GPS = 0 ]
    then
      echo -n " · "
    fi
    echo -n "󰀛 ${temp}°C [<span color='#aaaaaa'>${humy}% ${pres}hPa</span>]"
  fi
  if [ $NO_IAQ = 0 ]
  then
    if [ $NO_GPS = 0 ] || [ $NO_TEMP = 0 ]
    then
      echo -n " · "
    fi
    echo -n "󰵃 ${iaq} [<span color='#aaaaaa'>${gasp}%</span>]"
  fi
  if [ $NO_UV = 0 ]
  then
    if [ $NO_GPS = 0 ] || [ $NO_TEMP = 0 ] || [ $NO_IAQ = 0 ]
    then
      echo -n " · "
    fi
    echo -n "󱟾 ${ulvi} [<span color='#aaaaaa'>${visb}lm</span>]"
  fi
  echo -n "\", \"tooltip\": \"\", \"alt\": \"\", \"class\": \"\" }"
else
  echo -n ""
fi

