#!/bin/sh
resp=$(curl --silent -H 'Content-Type: application/json' http://127.0.0.1:3232)
if [ -n "$resp" ]
then
  temp=$(echo $resp | jq '.temp' | xargs printf '%.*f\n' 1 $a)
  humy=$(echo $resp | jq '.humy' | xargs printf '%.*f\n' 1 $a)
  pres=$(echo $resp | jq '.pres' | xargs printf '%.*f\n' 1 $a)

  iaq=$(echo $resp | jq '.iaq' | xargs printf '%.*f\n' 1 $a)
  gasp=$(echo $resp | jq '.gasp' | xargs printf '%.*f\n' 1 $a)

  ulvi=$(echo $resp | jq '.ulvi' | xargs printf '%.*f\n' 1 $a)
  visb=$(echo $resp | jq '.visb' | xargs printf '%.*f\n' 1 $a)

  latt=$(echo $resp | jq '.latt' | xargs -I {} echo "{}*10^-7" | eva | xargs printf '%.*f\n' 8 $a)
  long=$(echo $resp | jq '.long' | xargs -I {} echo "{}*10^-7" | eva | xargs printf '%.*f\n' 8 $a)
  altt=$(echo $resp | jq '.altt' | xargs -I {} echo "{}/1000" | bc )

  echo -n "{\"text\": \" <span color='#aaaaaa'>${altt}m</span> [<span color='#aaaaaa'>${latt} ${long}</span>] · 󰀛 <span color='#aaaaaa'>${temp}°C</span> [<span color='#aaaaaa'>${humy}% ${pres}hPa</span>] · 󰵃 <span color='#aaaaaa'>${iaq}</span> [<span color='#aaaaaa'>${gasp}%</span>] · 󱟾 <span color='#aaaaaa'>${ulvi}</span> [<span color='#aaaaaa'>${visb}lm</span>]\", \"tooltip\": \"\", \"alt\": \"\", \"class\": \"\" }"
else
  echo -n ""
fi

